# Generated by Django 2.0.6 on 2018-06-21 19:08

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollpage',
            name='questions',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='polls.Question'),
        ),
    ]
